### ISSUE TITLE
.NET 4.7.2 - The response ended prematurely

### ISSUE THREAD

**Issue by Martin-Thiele** [russcam/qdrant-dotnet-client#6]
The example snippet

```
var address = GrpcChannel.ForAddress("http://localhost:6334");
var client = new QdrantGrpcClient(address);
// check qdrant is healthy
var healthResponse = client.Qdrant.HealthCheck(new HealthCheckRequest());
```
fails in .NET 4.7.2 with the following exception tree
```
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The response ended prematurely.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.") -> An error occurred while sending the request. -> The response ended prematurely.
```

it works fine on .NET 6

**Comment by russcam** [comment]
.NET Framework has limited supported for gRPC over HTTP/2, but it can be enabled by

- Configuring qdrant to use TLS, and you must use HTTPS, so you may want to [set up cert validation](https://forloop.co.uk/qdrant-dotnet-client/documentation/connecting.html?tabs=linux#validating-self-signed-tls-certificates)
- Referencing [Grpc.Net.Client.Web](https://www.nuget.org/packages/Grpc.Net.Client.Web) and configuring `GrpcWebHandler` as the `HttpHandler`
- Referencing [System.Net.Http.WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) 6.0.1 or later, and configuring `WinHttpHandler` as the inner handler for  `GrpcWebHandler`

See [Configure gRPC-Web with the .NET gRPC client](https://learn.microsoft.com/en-au/aspnet/core/grpc/grpcweb?view=aspnetcore-7.0#configure-grpc-web-with-the-net-grpc-client) and Use [gRPC client with .NET Standard 2.0](https://learn.microsoft.com/en-au/aspnet/core/grpc/netstandard?view=aspnetcore-7.0#net-framework) for further details.

The following works:

```csharp
var channel = GrpcChannel.ForAddress("https://localhost:51379", new GrpcChannelOptions
{
    HttpHandler = new GrpcWebHandler(new WinHttpHandler
    { 
        ServerCertificateValidationCallback =
            CertificateValidation.Thumbprint("28fb5a5ef762238ec259ae46720180b855be3274ff39a9edc1b465a5b46a4546")
    })
});
var callInvoker = channel.Intercept(metadata =>
{
    metadata.Add("api-key", "password!");
    return metadata;
});


var client = new QdrantGrpcClient(callInvoker);
// check qdrant is healthy
var healthResponse = client.Qdrant.HealthCheck(new HealthCheckRequest());
```

I'll add this to the docs.

A JSON based HTTP client is also in the works.
